### ISSUE TITLE
Add `printf`, `sprintf`, `fprintf` and more features from libc.

### ISSUE THREAD

**Issue by ghost** [wbbradley/ace#29]
@wbbradley @yetamrra 

Can you add `printf`, `sprintf`, `fprintf` and more features from libc?

**Comment by wbbradley** [comment]
Not sure what you're deeper objective is here. Zion supports string interpolation with syntax like `"Hello ${planet_name}."`

**Comment by wbbradley** [comment]
Let me know if you have a goal you'd like to accomplish in mind.
