### ISSUE TITLE
Few questions.

### ISSUE THREAD

**Issue by ghost** [wbbradley/ace#30]
@wbbradley 

I have a few questions:

1. Is there any command line arguments parser (`argc`, `argv`)?

2. How to read user input?

3. Where I can find some docs?

Thanks.

**Comment by wbbradley** [comment]
Hi @t0md3an! Thanks for asking.

1. You can access the command line via (for example)

```
import sys {args}

fn main() {
  print(args)
}
```

the type of `args` in that example is `[String]` or `Vector String` (same thing).

2. currently I've got `readline` integrated. Here's an example of a program that will read and echo user input:

```
import readline {readline}

fn main() {
  if readline("What's your name? ") is Just(name) {
    print("Hello ${name}!")
  } else {
    print("OK, I understand privacy is important.")
  }
}
```

Also, take a look at [test_readline.zion](https://github.com/zionlang/zion/tree/master/tests/test_readline.zion) to see a super hacky way of writing a quine-like in Zion.

3. Currently there are no documents, outside of [tests](https://github.com/zionlang/zion/tree/master/tests), the man page (run `man zion`), the [standard library](https://github.com/zionlang/zion/tree/master/lib) and the [development](https://github.com/zionlang/zion/tree/master/DEVELOPMENT.md) page (which I just started on). I've been plodding away to just getting things to a point that I'm happy with so I haven't invested any real time/energy in docs yet.
